async def loading(kumbidi_swami, a, b, wait):
    c = await kumbidi_swami.message.reply(f"{a}{a}{a}")
    await wait(0.2)
    d = await c.edit(f"{b}{a}{a}")
    await wait(0.2)
    e = await d.edit(f"{b}{b}{a}")
    await wait(0.2)
    f = await d.edit(f"{b}{b}{b}")
    await wait(0.2)
    await f.delete()
